import 'package:flutter/material.dart';
import '../models/typography_scale_tokens.dart';

class CloudSqlCatalogModal extends StatefulWidget {
  final VoidCallback onDismissed;

  const CloudSqlCatalogModal({super.key, required this.onDismissed});

  /// Static trigger helper launching the adaptive overlay
  static void show(BuildContext context) {
    final isDesktop = MediaQuery.of(context).size.width >= 600;

    if (isDesktop) {
      // Desktop Layout: Top-level Centered Modal Sheet Card
      showDialog(
        context: context,
        barrierDismissible: true,
        builder: (ctx) => Dialog(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16.0),
          ),
          child: SizedBox(
            width: 520,
            child: CloudSqlCatalogModal(
              onDismissed: () => Navigator.of(ctx).pop(),
            ),
          ),
        ),
      );
    } else {
      // Mobile Viewport: Fixed Full-Screen Sub-View with Native Edge-Swipe Dismiss
      Navigator.of(context).push(
        MaterialPageRoute(
          builder: (ctx) => Scaffold(
            body: SafeArea(
              child: Dismissible(
                key: const Key('full_screen_edge_dismiss'),
                direction:
                    DismissDirection.startToEnd, // Edge-swipe dismiss gesture
                onDismissed: (_) => Navigator.of(ctx).pop(),
                child: CloudSqlCatalogModal(
                  onDismissed: () => Navigator.of(ctx).pop(),
                ),
              ),
            ),
          ),
        ),
      );
    }
  }

  @override
  State<CloudSqlCatalogModal> createState() => _CloudSqlCatalogModalState();
}

class _CloudSqlCatalogModalState extends State<CloudSqlCatalogModal> {
  final _formKey = GlobalKey<FormState>();
  final TypographyScaleTokens _typeTokens = TypographyScaleTokens();

  final TextEditingController _termController = TextEditingController(
    text: 'Customer Lifetime Value (CLV)',
  );
  final TextEditingController _definitionController = TextEditingController(
    text:
        'Calculated cumulative net revenue generated by a single user entity.',
  );
  final TextEditingController _schemaIdController = TextEditingController(
    text: 'tbl_crm_customer_metrics_v2',
  );

  bool _isDeploying = false;

  @override
  void dispose() {
    _termController.dispose();
    _definitionController.dispose();
    _schemaIdController.dispose();
    super.dispose();
  }

  void _saveToCloudSqlCatalog() {
    if (_formKey.currentState!.validate()) {
      setState(() => _isDeploying = true);

      Future.delayed(const Duration(milliseconds: 600), () {
        if (mounted) {
          setState(() => _isDeploying = false);
          widget.onDismissed();
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text(
                'Catalog Mapping Persisted to Cloud SQL JSON Table!',
              ),
              backgroundColor: Colors.green,
            ),
          );
        }
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colorScheme = theme.colorScheme;
    final isDesktop = MediaQuery.of(context).size.width >= 600;

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header Bar
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Row(
                children: [
                  Icon(
                    Icons.storage_rounded,
                    color: colorScheme.primary,
                    size: 24,
                  ),
                  const SizedBox(width: 8),
                  Text(
                    'Cloud SQL Catalog Entry',
                    style: theme.textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ],
              ),
              IconButton(
                icon: const Icon(Icons.close_rounded),
                onPressed: widget.onDismissed,
              ),
            ],
          ),

          if (!isDesktop)
            Padding(
              padding: const EdgeInsets.only(bottom: 8.0),
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: Colors.blue.shade50,
                  borderRadius: BorderRadius.circular(4),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: const [
                    Icon(Icons.swipe_right, size: 14, color: Colors.blue),
                    SizedBox(width: 4),
                    Text(
                      'Swipe right from edge to dismiss',
                      style: TextStyle(fontSize: 11, color: Colors.blue),
                    ),
                  ],
                ),
              ),
            ),

          const Divider(),
          const SizedBox(height: 12),

          // Single-Column Layout Grid
          Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Input 1: Logical Business Term
                _buildFormLabel('Logical Business Term'),
                const SizedBox(height: 6),
                _buildOutlinedInputField(
                  controller: _termController,
                  hintText: 'e.g., Gross Revenue',
                ),

                const SizedBox(height: 16),

                // Input 2: Downstream Schema ID
                _buildFormLabel('Downstream Database Schema ID'),
                const SizedBox(height: 6),
                _buildOutlinedInputField(
                  controller: _schemaIdController,
                  hintText: 'e.g., schema_finance.fact_orders',
                ),

                const SizedBox(height: 16),

                // Input 3: Logical Business Definition
                _buildFormLabel('Logical Business Definition'),
                const SizedBox(height: 6),
                _buildOutlinedInputField(
                  controller: _definitionController,
                  hintText: 'Enter complete business definition',
                  maxLines: 3,
                ),

                const SizedBox(height: 24),

                // Submit Trigger (>= 48dp Touch Target Constraint)
                ConstrainedBox(
                  constraints: const BoxConstraints(
                    minHeight: 48.0,
                    minWidth: 48.0,
                  ),
                  child: SizedBox(
                    width: double.infinity,
                    height: 48.0,
                    child: ElevatedButton.icon(
                      style: ElevatedButton.styleFrom(
                        backgroundColor: colorScheme.primary,
                        foregroundColor: colorScheme.onPrimary,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(8.0),
                        ),
                      ),
                      onPressed: _isDeploying ? null : _saveToCloudSqlCatalog,
                      icon: _isDeploying
                          ? const SizedBox(
                              width: 18,
                              height: 18,
                              child: CircularProgressIndicator(
                                color: Colors.white,
                                strokeWidth: 2,
                              ),
                            )
                          : const Icon(Icons.cloud_upload_rounded),
                      label: Text(
                        _isDeploying
                            ? 'Persisting Catalog Data...'
                            : 'Persist JSON Catalog Entry',
                        style: const TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),

          const SizedBox(height: 24),

          // FIXED M3 TYPOGRAPHY SCALE METADATA SUMMARY
          Text(
            'Enforced M3 Typography Scale Tokens',
            style: theme.textTheme.titleSmall?.copyWith(
              fontWeight: FontWeight.bold,
            ),
          ),
          const SizedBox(height: 8),

          Card.outlined(
            child: Padding(
              padding: const EdgeInsets.all(12.0),
              child: Column(
                children: [
                  _buildTypeMetaRow('Font Name', _typeTokens.fontName),
                  const Divider(height: 12),
                  _buildTypeMetaRow(
                    'Font Size',
                    '${_typeTokens.fontSize.toInt()}pt (M3 bodyMedium)',
                  ),
                  const Divider(height: 12),
                  _buildTypeMetaRow(
                    'Line Height',
                    '${_typeTokens.lineHeight} (20pt)',
                  ),
                  const Divider(height: 12),
                  _buildTypeMetaRow(
                    'Font Weight',
                    _typeTokens.fontWeight.toString(),
                  ),
                  const Divider(height: 12),
                  _buildTypeMetaRow('Font File Path', _typeTokens.fontFilePath),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFormLabel(String label) {
    return Text(
      label,
      // REQUIREMENT: Enforce M3 bodyMedium token mapped precisely to 14pt
      style: _typeTokens.bodyMedium14pt.copyWith(fontWeight: FontWeight.bold),
    );
  }

  Widget _buildOutlinedInputField({
    required TextEditingController controller,
    required String hintText,
    int maxLines = 1,
  }) {
    // REQUIREMENT: Limit form text parameters to >= 48dp interaction targets
    return ConstrainedBox(
      constraints: const BoxConstraints(minHeight: 48.0, minWidth: 48.0),
      child: TextFormField(
        controller: controller,
        maxLines: maxLines,
        // REQUIREMENT: Enforce M3 bodyMedium token mapped precisely to 14pt
        style: _typeTokens.bodyMedium14pt,
        validator: (value) {
          if (value == null || value.trim().isEmpty) {
            return 'Field is required.';
          }
          return null;
        },
        decoration: InputDecoration(
          hintText: hintText,
          hintStyle: _typeTokens.bodyMedium14pt.copyWith(color: Colors.grey),
          border: const OutlineInputBorder(),
          contentPadding: const EdgeInsets.symmetric(
            horizontal: 16.0,
            vertical: 14.0,
          ),
        ),
      ),
    );
  }

  Widget _buildTypeMetaRow(String label, String value) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: const TextStyle(
            fontSize: 11,
            fontWeight: FontWeight.bold,
            color: Colors.grey,
          ),
        ),
        Expanded(
          child: Text(
            value,
            textAlign: TextAlign.end,
            overflow: TextOverflow.ellipsis,
            style: const TextStyle(
              fontSize: 11,
              fontFamily: 'monospace',
              color: Colors.blueGrey,
            ),
          ),
        ),
      ],
    );
  }
}
